package com.lbspak.model.appmodules;

import oracle.jbo.server.ApplicationModuleImpl;
import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon Oct 24 07:16:45 PDT 2016
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class LBSAppModuleImpl extends ApplicationModuleImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public LBSAppModuleImpl() {
    }

    /**
     * Container's getter for VOFndUsers1.
     * @return VOFndUsers1
     */
    public ViewObjectImpl getVOFndUsers1() {
        return (ViewObjectImpl)findViewObject("VOFndUsers1");
    }

    /**
     * Container's getter for VOMediaPlan1.
     * @return VOMediaPlan1
     */
    public ViewObjectImpl getVOMediaPlan1() {
        return (ViewObjectImpl)findViewObject("VOMediaPlan1");
    }
}
