package com.lbspak.model.appmodules;

import oracle.jbo.server.ApplicationModuleImpl;
import oracle.jbo.server.ViewLinkImpl;
import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon Oct 24 07:16:45 PDT 2016
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class LBSAppModuleImpl extends ApplicationModuleImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public LBSAppModuleImpl() {
    }

    /**
     * Container's getter for VOFndUsers1.
     * @return VOFndUsers1
     */
    public ViewObjectImpl getVOFndUsers1() {
        return (ViewObjectImpl)findViewObject("VOFndUsers1");
    }


    /**
     * Container's getter for VOCustomers1.
     * @return VOCustomers1
     */
    public ViewObjectImpl getVOCustomers1() {
        return (ViewObjectImpl)findViewObject("VOCustomers1");
    }

    /**
     * Container's getter for VOMediaPlanHeader1.
     * @return VOMediaPlanHeader1
     */
    public ViewObjectImpl getVOMediaPlanHeader1() {
        return (ViewObjectImpl)findViewObject("VOMediaPlanHeader1");
    }

    /**
     * Container's getter for VOMediaPlanLine1.
     * @return VOMediaPlanLine1
     */
    public ViewObjectImpl getVOMediaPlanLine1() {
        return (ViewObjectImpl)findViewObject("VOMediaPlanLine1");
    }

    /**
     * Container's getter for VOMediaPlanHeader2.
     * @return VOMediaPlanHeader2
     */
    public ViewObjectImpl getVOMediaPlanHeader2() {
        return (ViewObjectImpl)findViewObject("VOMediaPlanHeader2");
    }

    /**
     * Container's getter for VOMediaPlanLine2.
     * @return VOMediaPlanLine2
     */
    public ViewObjectImpl getVOMediaPlanLine2() {
        return (ViewObjectImpl)findViewObject("VOMediaPlanLine2");
    }

    /**
     * Container's getter for VLMediaPlanHeader2Lines.
     * @return VLMediaPlanHeader2Lines
     */
    public ViewLinkImpl getVLMediaPlanHeader2Lines() {
        return (ViewLinkImpl)findViewLink("VLMediaPlanHeader2Lines");
    }
}
