package com.lbspak.model.electronic_media;

import oracle.jbo.AttributeList;
import oracle.jbo.Key;
import oracle.jbo.domain.Date;
import oracle.jbo.domain.Number;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.EntityDefImpl;
import oracle.jbo.server.EntityImpl;
import oracle.jbo.server.SequenceImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sat Oct 29 07:17:18 PDT 2016
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class EOMediaPlanHeaderImpl extends EntityImpl {
    private static EntityDefImpl mDefinitionObject;

    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    public enum AttributesEnum {
        PlanId {
            public Object get(EOMediaPlanHeaderImpl obj) {
                return obj.getPlanId();
            }

            public void put(EOMediaPlanHeaderImpl obj, Object value) {
                obj.setPlanId((Number)value);
            }
        }
        ,
        PlanNumber {
            public Object get(EOMediaPlanHeaderImpl obj) {
                return obj.getPlanNumber();
            }

            public void put(EOMediaPlanHeaderImpl obj, Object value) {
                obj.setPlanNumber((Number)value);
            }
        }
        ,
        BillToCustomer {
            public Object get(EOMediaPlanHeaderImpl obj) {
                return obj.getBillToCustomer();
            }

            public void put(EOMediaPlanHeaderImpl obj, Object value) {
                obj.setBillToCustomer((String)value);
            }
        }
        ,
        PlanStartDate {
            public Object get(EOMediaPlanHeaderImpl obj) {
                return obj.getPlanStartDate();
            }

            public void put(EOMediaPlanHeaderImpl obj, Object value) {
                obj.setPlanStartDate((Date)value);
            }
        }
        ,
        PlanEndDate {
            public Object get(EOMediaPlanHeaderImpl obj) {
                return obj.getPlanEndDate();
            }

            public void put(EOMediaPlanHeaderImpl obj, Object value) {
                obj.setPlanEndDate((Date)value);
            }
        }
        ,
        CreationDate {
            public Object get(EOMediaPlanHeaderImpl obj) {
                return obj.getCreationDate();
            }

            public void put(EOMediaPlanHeaderImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        CreatedBy {
            public Object get(EOMediaPlanHeaderImpl obj) {
                return obj.getCreatedBy();
            }

            public void put(EOMediaPlanHeaderImpl obj, Object value) {
                obj.setCreatedBy((Number)value);
            }
        }
        ,
        UpdatedDate {
            public Object get(EOMediaPlanHeaderImpl obj) {
                return obj.getUpdatedDate();
            }

            public void put(EOMediaPlanHeaderImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        UpdatedBy {
            public Object get(EOMediaPlanHeaderImpl obj) {
                return obj.getUpdatedBy();
            }

            public void put(EOMediaPlanHeaderImpl obj, Object value) {
                obj.setUpdatedBy((Number)value);
            }
        }
        ,
        DocumentRevision {
            public Object get(EOMediaPlanHeaderImpl obj) {
                return obj.getDocumentRevision();
            }

            public void put(EOMediaPlanHeaderImpl obj, Object value) {
                obj.setDocumentRevision((Number)value);
            }
        }
        ;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        public abstract Object get(EOMediaPlanHeaderImpl object);

        public abstract void put(EOMediaPlanHeaderImpl object, Object value);

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static final int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int PLANID = AttributesEnum.PlanId.index();
    public static final int PLANNUMBER = AttributesEnum.PlanNumber.index();
    public static final int BILLTOCUSTOMER = AttributesEnum.BillToCustomer.index();
    public static final int PLANSTARTDATE = AttributesEnum.PlanStartDate.index();
    public static final int PLANENDDATE = AttributesEnum.PlanEndDate.index();
    public static final int CREATIONDATE = AttributesEnum.CreationDate.index();
    public static final int CREATEDBY = AttributesEnum.CreatedBy.index();
    public static final int UPDATEDDATE = AttributesEnum.UpdatedDate.index();
    public static final int UPDATEDBY = AttributesEnum.UpdatedBy.index();
    public static final int DOCUMENTREVISION = AttributesEnum.DocumentRevision.index();

    /**
     * This is the default constructor (do not remove).
     */
    public EOMediaPlanHeaderImpl() {
    }


    /**
     * @return the definition object for this instance class.
     */
    public static synchronized EntityDefImpl getDefinitionObject() {
        if (mDefinitionObject == null) {
            mDefinitionObject = EntityDefImpl.findDefObject("com.lbspak.model.electronic_media.EOMediaPlanHeader");
        }
        return mDefinitionObject;
    }

    /**
     * Gets the attribute value for PlanId, using the alias name PlanId.
     * @return the PlanId
     */
    public Number getPlanId() {
        return (Number)getAttributeInternal(PLANID);
    }

    /**
     * Sets <code>value</code> as the attribute value for PlanId.
     * @param value value to set the PlanId
     */
    public void setPlanId(Number value) {
        setAttributeInternal(PLANID, value);
    }

    /**
     * Gets the attribute value for PlanNumber, using the alias name PlanNumber.
     * @return the PlanNumber
     */
    public Number getPlanNumber() {
        return (Number)getAttributeInternal(PLANNUMBER);
    }

    /**
     * Sets <code>value</code> as the attribute value for PlanNumber.
     * @param value value to set the PlanNumber
     */
    public void setPlanNumber(Number value) {
        setAttributeInternal(PLANNUMBER, value);
    }

    /**
     * Gets the attribute value for BillToCustomer, using the alias name BillToCustomer.
     * @return the BillToCustomer
     */
    public String getBillToCustomer() {
        return (String)getAttributeInternal(BILLTOCUSTOMER);
    }

    /**
     * Sets <code>value</code> as the attribute value for BillToCustomer.
     * @param value value to set the BillToCustomer
     */
    public void setBillToCustomer(String value) {
        setAttributeInternal(BILLTOCUSTOMER, value);
    }

    /**
     * Gets the attribute value for PlanStartDate, using the alias name PlanStartDate.
     * @return the PlanStartDate
     */
    public Date getPlanStartDate() {
        return (Date)getAttributeInternal(PLANSTARTDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for PlanStartDate.
     * @param value value to set the PlanStartDate
     */
    public void setPlanStartDate(Date value) {
        setAttributeInternal(PLANSTARTDATE, value);
    }

    /**
     * Gets the attribute value for PlanEndDate, using the alias name PlanEndDate.
     * @return the PlanEndDate
     */
    public Date getPlanEndDate() {
        return (Date)getAttributeInternal(PLANENDDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for PlanEndDate.
     * @param value value to set the PlanEndDate
     */
    public void setPlanEndDate(Date value) {
        setAttributeInternal(PLANENDDATE, value);
    }

    /**
     * Gets the attribute value for CreationDate, using the alias name CreationDate.
     * @return the CreationDate
     */
    public Date getCreationDate() {
        return (Date)getAttributeInternal(CREATIONDATE);
    }


    /**
     * Gets the attribute value for CreatedBy, using the alias name CreatedBy.
     * @return the CreatedBy
     */
    public Number getCreatedBy() {
        return (Number)getAttributeInternal(CREATEDBY);
    }


    /**
     * Sets <code>value</code> as the attribute value for CreatedBy.
     * @param value value to set the CreatedBy
     */
    public void setCreatedBy(Number value) {
        setAttributeInternal(CREATEDBY, value);
    }

    /**
     * Gets the attribute value for UpdatedDate, using the alias name UpdatedDate.
     * @return the UpdatedDate
     */
    public Date getUpdatedDate() {
        return (Date)getAttributeInternal(UPDATEDDATE);
    }


    /**
     * Gets the attribute value for UpdatedBy, using the alias name UpdatedBy.
     * @return the UpdatedBy
     */
    public Number getUpdatedBy() {
        return (Number)getAttributeInternal(UPDATEDBY);
    }


    /**
     * Sets <code>value</code> as the attribute value for UpdatedBy.
     * @param value value to set the UpdatedBy
     */
    public void setUpdatedBy(Number value) {
        setAttributeInternal(UPDATEDBY, value);
    }

    /**
     * Gets the attribute value for DocumentRevision, using the alias name DocumentRevision.
     * @return the DocumentRevision
     */
    public Number getDocumentRevision() {
        return (Number)getAttributeInternal(DOCUMENTREVISION);
    }

    /**
     * Sets <code>value</code> as the attribute value for DocumentRevision.
     * @param value value to set the DocumentRevision
     */
    public void setDocumentRevision(Number value) {
        setAttributeInternal(DOCUMENTREVISION, value);
    }

    /**
     * getAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param attrDef the attribute

     * @return the attribute value
     * @throws Exception
     */
    protected Object getAttrInvokeAccessor(int index,
                                           AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            return AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].get(this);
        }
        return super.getAttrInvokeAccessor(index, attrDef);
    }

    /**
     * setAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param value the value to assign to the attribute
     * @param attrDef the attribute

     * @throws Exception
     */
    protected void setAttrInvokeAccessor(int index, Object value,
                                         AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].put(this, value);
            return;
        }
        super.setAttrInvokeAccessor(index, value, attrDef);
    }


    /**
     * @param planId key constituent

     * @return a Key object based on given key constituents.
     */
    public static Key createPrimaryKey(Number planId) {
        return new Key(new Object[]{planId});
    }

    @Override
    protected void create(AttributeList attributeList) {
        super.create(attributeList);
        SequenceImpl seqHeader =  new SequenceImpl("media_plan_header_seq",getDBTransaction());
        setPlanId(seqHeader.getSequenceNumber());
    }
}
