package com.lbspak.model.electronic_media;

import oracle.jbo.AttributeList;
import oracle.jbo.Key;
import oracle.jbo.domain.Date;
import oracle.jbo.domain.Number;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.EntityDefImpl;
import oracle.jbo.server.EntityImpl;
import oracle.jbo.server.SequenceImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sat Oct 29 07:28:53 PDT 2016
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class EOMediaPlanLineImpl extends EntityImpl {
    private static EntityDefImpl mDefinitionObject;

    @Override
    protected void create(AttributeList attributeList) {
        super.create(attributeList);
        SequenceImpl seqHeader =  new SequenceImpl("media_plan_line_seq",getDBTransaction());
        setPlanLineId(seqHeader.getSequenceNumber());
    }

    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    public enum AttributesEnum {
        PlanLineId {
            public Object get(EOMediaPlanLineImpl obj) {
                return obj.getPlanLineId();
            }

            public void put(EOMediaPlanLineImpl obj, Object value) {
                obj.setPlanLineId((Number)value);
            }
        }
        ,
        PlanId {
            public Object get(EOMediaPlanLineImpl obj) {
                return obj.getPlanId();
            }

            public void put(EOMediaPlanLineImpl obj, Object value) {
                obj.setPlanId((Number)value);
            }
        }
        ,
        VendorId {
            public Object get(EOMediaPlanLineImpl obj) {
                return obj.getVendorId();
            }

            public void put(EOMediaPlanLineImpl obj, Object value) {
                obj.setVendorId((Number)value);
            }
        }
        ,
        VendorSiteId {
            public Object get(EOMediaPlanLineImpl obj) {
                return obj.getVendorSiteId();
            }

            public void put(EOMediaPlanLineImpl obj, Object value) {
                obj.setVendorSiteId((Number)value);
            }
        }
        ,
        TimeSlot {
            public Object get(EOMediaPlanLineImpl obj) {
                return obj.getTimeSlot();
            }

            public void put(EOMediaPlanLineImpl obj, Object value) {
                obj.setTimeSlot((String)value);
            }
        }
        ,
        Brand {
            public Object get(EOMediaPlanLineImpl obj) {
                return obj.getBrand();
            }

            public void put(EOMediaPlanLineImpl obj, Object value) {
                obj.setBrand((String)value);
            }
        }
        ,
        AdTitle {
            public Object get(EOMediaPlanLineImpl obj) {
                return obj.getAdTitle();
            }

            public void put(EOMediaPlanLineImpl obj, Object value) {
                obj.setAdTitle((String)value);
            }
        }
        ,
        AdDuration {
            public Object get(EOMediaPlanLineImpl obj) {
                return obj.getAdDuration();
            }

            public void put(EOMediaPlanLineImpl obj, Object value) {
                obj.setAdDuration((Number)value);
            }
        }
        ,
        Day1 {
            public Object get(EOMediaPlanLineImpl obj) {
                return obj.getDay1();
            }

            public void put(EOMediaPlanLineImpl obj, Object value) {
                obj.setDay1((Number)value);
            }
        }
        ,
        Day2 {
            public Object get(EOMediaPlanLineImpl obj) {
                return obj.getDay2();
            }

            public void put(EOMediaPlanLineImpl obj, Object value) {
                obj.setDay2((Number)value);
            }
        }
        ,
        Day3 {
            public Object get(EOMediaPlanLineImpl obj) {
                return obj.getDay3();
            }

            public void put(EOMediaPlanLineImpl obj, Object value) {
                obj.setDay3((Number)value);
            }
        }
        ,
        Day4 {
            public Object get(EOMediaPlanLineImpl obj) {
                return obj.getDay4();
            }

            public void put(EOMediaPlanLineImpl obj, Object value) {
                obj.setDay4((Number)value);
            }
        }
        ,
        Day5 {
            public Object get(EOMediaPlanLineImpl obj) {
                return obj.getDay5();
            }

            public void put(EOMediaPlanLineImpl obj, Object value) {
                obj.setDay5((Number)value);
            }
        }
        ,
        Day6 {
            public Object get(EOMediaPlanLineImpl obj) {
                return obj.getDay6();
            }

            public void put(EOMediaPlanLineImpl obj, Object value) {
                obj.setDay6((Number)value);
            }
        }
        ,
        Day7 {
            public Object get(EOMediaPlanLineImpl obj) {
                return obj.getDay7();
            }

            public void put(EOMediaPlanLineImpl obj, Object value) {
                obj.setDay7((Number)value);
            }
        }
        ,
        Day8 {
            public Object get(EOMediaPlanLineImpl obj) {
                return obj.getDay8();
            }

            public void put(EOMediaPlanLineImpl obj, Object value) {
                obj.setDay8((Number)value);
            }
        }
        ,
        Day9 {
            public Object get(EOMediaPlanLineImpl obj) {
                return obj.getDay9();
            }

            public void put(EOMediaPlanLineImpl obj, Object value) {
                obj.setDay9((Number)value);
            }
        }
        ,
        Day10 {
            public Object get(EOMediaPlanLineImpl obj) {
                return obj.getDay10();
            }

            public void put(EOMediaPlanLineImpl obj, Object value) {
                obj.setDay10((Number)value);
            }
        }
        ,
        Day11 {
            public Object get(EOMediaPlanLineImpl obj) {
                return obj.getDay11();
            }

            public void put(EOMediaPlanLineImpl obj, Object value) {
                obj.setDay11((Number)value);
            }
        }
        ,
        Day12 {
            public Object get(EOMediaPlanLineImpl obj) {
                return obj.getDay12();
            }

            public void put(EOMediaPlanLineImpl obj, Object value) {
                obj.setDay12((Number)value);
            }
        }
        ,
        Day13 {
            public Object get(EOMediaPlanLineImpl obj) {
                return obj.getDay13();
            }

            public void put(EOMediaPlanLineImpl obj, Object value) {
                obj.setDay13((Number)value);
            }
        }
        ,
        Day14 {
            public Object get(EOMediaPlanLineImpl obj) {
                return obj.getDay14();
            }

            public void put(EOMediaPlanLineImpl obj, Object value) {
                obj.setDay14((Number)value);
            }
        }
        ,
        Day15 {
            public Object get(EOMediaPlanLineImpl obj) {
                return obj.getDay15();
            }

            public void put(EOMediaPlanLineImpl obj, Object value) {
                obj.setDay15((Number)value);
            }
        }
        ,
        Day16 {
            public Object get(EOMediaPlanLineImpl obj) {
                return obj.getDay16();
            }

            public void put(EOMediaPlanLineImpl obj, Object value) {
                obj.setDay16((Number)value);
            }
        }
        ,
        Day17 {
            public Object get(EOMediaPlanLineImpl obj) {
                return obj.getDay17();
            }

            public void put(EOMediaPlanLineImpl obj, Object value) {
                obj.setDay17((Number)value);
            }
        }
        ,
        Day18 {
            public Object get(EOMediaPlanLineImpl obj) {
                return obj.getDay18();
            }

            public void put(EOMediaPlanLineImpl obj, Object value) {
                obj.setDay18((Number)value);
            }
        }
        ,
        Day19 {
            public Object get(EOMediaPlanLineImpl obj) {
                return obj.getDay19();
            }

            public void put(EOMediaPlanLineImpl obj, Object value) {
                obj.setDay19((Number)value);
            }
        }
        ,
        Day20 {
            public Object get(EOMediaPlanLineImpl obj) {
                return obj.getDay20();
            }

            public void put(EOMediaPlanLineImpl obj, Object value) {
                obj.setDay20((Number)value);
            }
        }
        ,
        Day21 {
            public Object get(EOMediaPlanLineImpl obj) {
                return obj.getDay21();
            }

            public void put(EOMediaPlanLineImpl obj, Object value) {
                obj.setDay21((Number)value);
            }
        }
        ,
        Day22 {
            public Object get(EOMediaPlanLineImpl obj) {
                return obj.getDay22();
            }

            public void put(EOMediaPlanLineImpl obj, Object value) {
                obj.setDay22((Number)value);
            }
        }
        ,
        Day23 {
            public Object get(EOMediaPlanLineImpl obj) {
                return obj.getDay23();
            }

            public void put(EOMediaPlanLineImpl obj, Object value) {
                obj.setDay23((Number)value);
            }
        }
        ,
        Day24 {
            public Object get(EOMediaPlanLineImpl obj) {
                return obj.getDay24();
            }

            public void put(EOMediaPlanLineImpl obj, Object value) {
                obj.setDay24((Number)value);
            }
        }
        ,
        Day25 {
            public Object get(EOMediaPlanLineImpl obj) {
                return obj.getDay25();
            }

            public void put(EOMediaPlanLineImpl obj, Object value) {
                obj.setDay25((Number)value);
            }
        }
        ,
        Day26 {
            public Object get(EOMediaPlanLineImpl obj) {
                return obj.getDay26();
            }

            public void put(EOMediaPlanLineImpl obj, Object value) {
                obj.setDay26((Number)value);
            }
        }
        ,
        Day27 {
            public Object get(EOMediaPlanLineImpl obj) {
                return obj.getDay27();
            }

            public void put(EOMediaPlanLineImpl obj, Object value) {
                obj.setDay27((Number)value);
            }
        }
        ,
        Day28 {
            public Object get(EOMediaPlanLineImpl obj) {
                return obj.getDay28();
            }

            public void put(EOMediaPlanLineImpl obj, Object value) {
                obj.setDay28((Number)value);
            }
        }
        ,
        Day29 {
            public Object get(EOMediaPlanLineImpl obj) {
                return obj.getDay29();
            }

            public void put(EOMediaPlanLineImpl obj, Object value) {
                obj.setDay29((Number)value);
            }
        }
        ,
        Day30 {
            public Object get(EOMediaPlanLineImpl obj) {
                return obj.getDay30();
            }

            public void put(EOMediaPlanLineImpl obj, Object value) {
                obj.setDay30((Number)value);
            }
        }
        ,
        Day31 {
            public Object get(EOMediaPlanLineImpl obj) {
                return obj.getDay31();
            }

            public void put(EOMediaPlanLineImpl obj, Object value) {
                obj.setDay31((Number)value);
            }
        }
        ,
        Day32 {
            public Object get(EOMediaPlanLineImpl obj) {
                return obj.getDay32();
            }

            public void put(EOMediaPlanLineImpl obj, Object value) {
                obj.setDay32((Number)value);
            }
        }
        ,
        Day33 {
            public Object get(EOMediaPlanLineImpl obj) {
                return obj.getDay33();
            }

            public void put(EOMediaPlanLineImpl obj, Object value) {
                obj.setDay33((Number)value);
            }
        }
        ,
        Day34 {
            public Object get(EOMediaPlanLineImpl obj) {
                return obj.getDay34();
            }

            public void put(EOMediaPlanLineImpl obj, Object value) {
                obj.setDay34((Number)value);
            }
        }
        ,
        Day35 {
            public Object get(EOMediaPlanLineImpl obj) {
                return obj.getDay35();
            }

            public void put(EOMediaPlanLineImpl obj, Object value) {
                obj.setDay35((Number)value);
            }
        }
        ,
        Day36 {
            public Object get(EOMediaPlanLineImpl obj) {
                return obj.getDay36();
            }

            public void put(EOMediaPlanLineImpl obj, Object value) {
                obj.setDay36((Number)value);
            }
        }
        ,
        Day37 {
            public Object get(EOMediaPlanLineImpl obj) {
                return obj.getDay37();
            }

            public void put(EOMediaPlanLineImpl obj, Object value) {
                obj.setDay37((Number)value);
            }
        }
        ,
        Day38 {
            public Object get(EOMediaPlanLineImpl obj) {
                return obj.getDay38();
            }

            public void put(EOMediaPlanLineImpl obj, Object value) {
                obj.setDay38((Number)value);
            }
        }
        ,
        Day39 {
            public Object get(EOMediaPlanLineImpl obj) {
                return obj.getDay39();
            }

            public void put(EOMediaPlanLineImpl obj, Object value) {
                obj.setDay39((Number)value);
            }
        }
        ,
        Day40 {
            public Object get(EOMediaPlanLineImpl obj) {
                return obj.getDay40();
            }

            public void put(EOMediaPlanLineImpl obj, Object value) {
                obj.setDay40((Number)value);
            }
        }
        ,
        Day41 {
            public Object get(EOMediaPlanLineImpl obj) {
                return obj.getDay41();
            }

            public void put(EOMediaPlanLineImpl obj, Object value) {
                obj.setDay41((Number)value);
            }
        }
        ,
        Day42 {
            public Object get(EOMediaPlanLineImpl obj) {
                return obj.getDay42();
            }

            public void put(EOMediaPlanLineImpl obj, Object value) {
                obj.setDay42((Number)value);
            }
        }
        ,
        Day43 {
            public Object get(EOMediaPlanLineImpl obj) {
                return obj.getDay43();
            }

            public void put(EOMediaPlanLineImpl obj, Object value) {
                obj.setDay43((Number)value);
            }
        }
        ,
        Day44 {
            public Object get(EOMediaPlanLineImpl obj) {
                return obj.getDay44();
            }

            public void put(EOMediaPlanLineImpl obj, Object value) {
                obj.setDay44((Number)value);
            }
        }
        ,
        Day45 {
            public Object get(EOMediaPlanLineImpl obj) {
                return obj.getDay45();
            }

            public void put(EOMediaPlanLineImpl obj, Object value) {
                obj.setDay45((Number)value);
            }
        }
        ,
        Day46 {
            public Object get(EOMediaPlanLineImpl obj) {
                return obj.getDay46();
            }

            public void put(EOMediaPlanLineImpl obj, Object value) {
                obj.setDay46((Number)value);
            }
        }
        ,
        Day47 {
            public Object get(EOMediaPlanLineImpl obj) {
                return obj.getDay47();
            }

            public void put(EOMediaPlanLineImpl obj, Object value) {
                obj.setDay47((Number)value);
            }
        }
        ,
        Day48 {
            public Object get(EOMediaPlanLineImpl obj) {
                return obj.getDay48();
            }

            public void put(EOMediaPlanLineImpl obj, Object value) {
                obj.setDay48((Number)value);
            }
        }
        ,
        Day49 {
            public Object get(EOMediaPlanLineImpl obj) {
                return obj.getDay49();
            }

            public void put(EOMediaPlanLineImpl obj, Object value) {
                obj.setDay49((Number)value);
            }
        }
        ,
        Day50 {
            public Object get(EOMediaPlanLineImpl obj) {
                return obj.getDay50();
            }

            public void put(EOMediaPlanLineImpl obj, Object value) {
                obj.setDay50((Number)value);
            }
        }
        ,
        Day51 {
            public Object get(EOMediaPlanLineImpl obj) {
                return obj.getDay51();
            }

            public void put(EOMediaPlanLineImpl obj, Object value) {
                obj.setDay51((Number)value);
            }
        }
        ,
        Day52 {
            public Object get(EOMediaPlanLineImpl obj) {
                return obj.getDay52();
            }

            public void put(EOMediaPlanLineImpl obj, Object value) {
                obj.setDay52((Number)value);
            }
        }
        ,
        Day53 {
            public Object get(EOMediaPlanLineImpl obj) {
                return obj.getDay53();
            }

            public void put(EOMediaPlanLineImpl obj, Object value) {
                obj.setDay53((Number)value);
            }
        }
        ,
        Day54 {
            public Object get(EOMediaPlanLineImpl obj) {
                return obj.getDay54();
            }

            public void put(EOMediaPlanLineImpl obj, Object value) {
                obj.setDay54((Number)value);
            }
        }
        ,
        Day55 {
            public Object get(EOMediaPlanLineImpl obj) {
                return obj.getDay55();
            }

            public void put(EOMediaPlanLineImpl obj, Object value) {
                obj.setDay55((Number)value);
            }
        }
        ,
        Day56 {
            public Object get(EOMediaPlanLineImpl obj) {
                return obj.getDay56();
            }

            public void put(EOMediaPlanLineImpl obj, Object value) {
                obj.setDay56((Number)value);
            }
        }
        ,
        Day57 {
            public Object get(EOMediaPlanLineImpl obj) {
                return obj.getDay57();
            }

            public void put(EOMediaPlanLineImpl obj, Object value) {
                obj.setDay57((Number)value);
            }
        }
        ,
        Day58 {
            public Object get(EOMediaPlanLineImpl obj) {
                return obj.getDay58();
            }

            public void put(EOMediaPlanLineImpl obj, Object value) {
                obj.setDay58((Number)value);
            }
        }
        ,
        Day59 {
            public Object get(EOMediaPlanLineImpl obj) {
                return obj.getDay59();
            }

            public void put(EOMediaPlanLineImpl obj, Object value) {
                obj.setDay59((Number)value);
            }
        }
        ,
        Day60 {
            public Object get(EOMediaPlanLineImpl obj) {
                return obj.getDay60();
            }

            public void put(EOMediaPlanLineImpl obj, Object value) {
                obj.setDay60((Number)value);
            }
        }
        ,
        RateType {
            public Object get(EOMediaPlanLineImpl obj) {
                return obj.getRateType();
            }

            public void put(EOMediaPlanLineImpl obj, Object value) {
                obj.setRateType((Number)value);
            }
        }
        ,
        RatePerMinute {
            public Object get(EOMediaPlanLineImpl obj) {
                return obj.getRatePerMinute();
            }

            public void put(EOMediaPlanLineImpl obj, Object value) {
                obj.setRatePerMinute((Number)value);
            }
        }
        ,
        DiscountPerMinute {
            public Object get(EOMediaPlanLineImpl obj) {
                return obj.getDiscountPerMinute();
            }

            public void put(EOMediaPlanLineImpl obj, Object value) {
                obj.setDiscountPerMinute((Number)value);
            }
        }
        ,
        PremiumPercentAge {
            public Object get(EOMediaPlanLineImpl obj) {
                return obj.getPremiumPercentAge();
            }

            public void put(EOMediaPlanLineImpl obj, Object value) {
                obj.setPremiumPercentAge((Number)value);
            }
        }
        ,
        ActualRate {
            public Object get(EOMediaPlanLineImpl obj) {
                return obj.getActualRate();
            }

            public void put(EOMediaPlanLineImpl obj, Object value) {
                obj.setActualRate((Number)value);
            }
        }
        ,
        CreditNoteAmount {
            public Object get(EOMediaPlanLineImpl obj) {
                return obj.getCreditNoteAmount();
            }

            public void put(EOMediaPlanLineImpl obj, Object value) {
                obj.setCreditNoteAmount((String)value);
            }
        }
        ,
        GstPercentAge {
            public Object get(EOMediaPlanLineImpl obj) {
                return obj.getGstPercentAge();
            }

            public void put(EOMediaPlanLineImpl obj, Object value) {
                obj.setGstPercentAge((String)value);
            }
        }
        ,
        GstClient {
            public Object get(EOMediaPlanLineImpl obj) {
                return obj.getGstClient();
            }

            public void put(EOMediaPlanLineImpl obj, Object value) {
                obj.setGstClient((String)value);
            }
        }
        ,
        AgencyCommissionClient {
            public Object get(EOMediaPlanLineImpl obj) {
                return obj.getAgencyCommissionClient();
            }

            public void put(EOMediaPlanLineImpl obj, Object value) {
                obj.setAgencyCommissionClient((String)value);
            }
        }
        ,
        CreatedBy {
            public Object get(EOMediaPlanLineImpl obj) {
                return obj.getCreatedBy();
            }

            public void put(EOMediaPlanLineImpl obj, Object value) {
                obj.setCreatedBy((Number)value);
            }
        }
        ,
        CreationDate {
            public Object get(EOMediaPlanLineImpl obj) {
                return obj.getCreationDate();
            }

            public void put(EOMediaPlanLineImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        UpdatedBy {
            public Object get(EOMediaPlanLineImpl obj) {
                return obj.getUpdatedBy();
            }

            public void put(EOMediaPlanLineImpl obj, Object value) {
                obj.setUpdatedBy((Number)value);
            }
        }
        ,
        UpdatedDate {
            public Object get(EOMediaPlanLineImpl obj) {
                return obj.getUpdatedDate();
            }

            public void put(EOMediaPlanLineImpl obj, Object value) {
                obj.setUpdatedDate((Date)value);
            }
        }
        ;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        public abstract Object get(EOMediaPlanLineImpl object);

        public abstract void put(EOMediaPlanLineImpl object, Object value);

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static final int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int PLANLINEID = AttributesEnum.PlanLineId.index();
    public static final int PLANID = AttributesEnum.PlanId.index();
    public static final int VENDORID = AttributesEnum.VendorId.index();
    public static final int VENDORSITEID = AttributesEnum.VendorSiteId.index();
    public static final int TIMESLOT = AttributesEnum.TimeSlot.index();
    public static final int BRAND = AttributesEnum.Brand.index();
    public static final int ADTITLE = AttributesEnum.AdTitle.index();
    public static final int ADDURATION = AttributesEnum.AdDuration.index();
    public static final int DAY1 = AttributesEnum.Day1.index();
    public static final int DAY2 = AttributesEnum.Day2.index();
    public static final int DAY3 = AttributesEnum.Day3.index();
    public static final int DAY4 = AttributesEnum.Day4.index();
    public static final int DAY5 = AttributesEnum.Day5.index();
    public static final int DAY6 = AttributesEnum.Day6.index();
    public static final int DAY7 = AttributesEnum.Day7.index();
    public static final int DAY8 = AttributesEnum.Day8.index();
    public static final int DAY9 = AttributesEnum.Day9.index();
    public static final int DAY10 = AttributesEnum.Day10.index();
    public static final int DAY11 = AttributesEnum.Day11.index();
    public static final int DAY12 = AttributesEnum.Day12.index();
    public static final int DAY13 = AttributesEnum.Day13.index();
    public static final int DAY14 = AttributesEnum.Day14.index();
    public static final int DAY15 = AttributesEnum.Day15.index();
    public static final int DAY16 = AttributesEnum.Day16.index();
    public static final int DAY17 = AttributesEnum.Day17.index();
    public static final int DAY18 = AttributesEnum.Day18.index();
    public static final int DAY19 = AttributesEnum.Day19.index();
    public static final int DAY20 = AttributesEnum.Day20.index();
    public static final int DAY21 = AttributesEnum.Day21.index();
    public static final int DAY22 = AttributesEnum.Day22.index();
    public static final int DAY23 = AttributesEnum.Day23.index();
    public static final int DAY24 = AttributesEnum.Day24.index();
    public static final int DAY25 = AttributesEnum.Day25.index();
    public static final int DAY26 = AttributesEnum.Day26.index();
    public static final int DAY27 = AttributesEnum.Day27.index();
    public static final int DAY28 = AttributesEnum.Day28.index();
    public static final int DAY29 = AttributesEnum.Day29.index();
    public static final int DAY30 = AttributesEnum.Day30.index();
    public static final int DAY31 = AttributesEnum.Day31.index();
    public static final int DAY32 = AttributesEnum.Day32.index();
    public static final int DAY33 = AttributesEnum.Day33.index();
    public static final int DAY34 = AttributesEnum.Day34.index();
    public static final int DAY35 = AttributesEnum.Day35.index();
    public static final int DAY36 = AttributesEnum.Day36.index();
    public static final int DAY37 = AttributesEnum.Day37.index();
    public static final int DAY38 = AttributesEnum.Day38.index();
    public static final int DAY39 = AttributesEnum.Day39.index();
    public static final int DAY40 = AttributesEnum.Day40.index();
    public static final int DAY41 = AttributesEnum.Day41.index();
    public static final int DAY42 = AttributesEnum.Day42.index();
    public static final int DAY43 = AttributesEnum.Day43.index();
    public static final int DAY44 = AttributesEnum.Day44.index();
    public static final int DAY45 = AttributesEnum.Day45.index();
    public static final int DAY46 = AttributesEnum.Day46.index();
    public static final int DAY47 = AttributesEnum.Day47.index();
    public static final int DAY48 = AttributesEnum.Day48.index();
    public static final int DAY49 = AttributesEnum.Day49.index();
    public static final int DAY50 = AttributesEnum.Day50.index();
    public static final int DAY51 = AttributesEnum.Day51.index();
    public static final int DAY52 = AttributesEnum.Day52.index();
    public static final int DAY53 = AttributesEnum.Day53.index();
    public static final int DAY54 = AttributesEnum.Day54.index();
    public static final int DAY55 = AttributesEnum.Day55.index();
    public static final int DAY56 = AttributesEnum.Day56.index();
    public static final int DAY57 = AttributesEnum.Day57.index();
    public static final int DAY58 = AttributesEnum.Day58.index();
    public static final int DAY59 = AttributesEnum.Day59.index();
    public static final int DAY60 = AttributesEnum.Day60.index();
    public static final int RATETYPE = AttributesEnum.RateType.index();
    public static final int RATEPERMINUTE = AttributesEnum.RatePerMinute.index();
    public static final int DISCOUNTPERMINUTE = AttributesEnum.DiscountPerMinute.index();
    public static final int PREMIUMPERCENTAGE = AttributesEnum.PremiumPercentAge.index();
    public static final int ACTUALRATE = AttributesEnum.ActualRate.index();
    public static final int CREDITNOTEAMOUNT = AttributesEnum.CreditNoteAmount.index();
    public static final int GSTPERCENTAGE = AttributesEnum.GstPercentAge.index();
    public static final int GSTCLIENT = AttributesEnum.GstClient.index();
    public static final int AGENCYCOMMISSIONCLIENT = AttributesEnum.AgencyCommissionClient.index();
    public static final int CREATEDBY = AttributesEnum.CreatedBy.index();
    public static final int CREATIONDATE = AttributesEnum.CreationDate.index();
    public static final int UPDATEDBY = AttributesEnum.UpdatedBy.index();
    public static final int UPDATEDDATE = AttributesEnum.UpdatedDate.index();

    /**
     * This is the default constructor (do not remove).
     */
    public EOMediaPlanLineImpl() {
    }


    /**
     * @return the definition object for this instance class.
     */
    public static synchronized EntityDefImpl getDefinitionObject() {
        if (mDefinitionObject == null) {
            mDefinitionObject = EntityDefImpl.findDefObject("com.lbspak.model.electronic_media.EOMediaPlanLine");
        }
        return mDefinitionObject;
    }

    /**
     * Gets the attribute value for PlanLineId, using the alias name PlanLineId.
     * @return the PlanLineId
     */
    public Number getPlanLineId() {
        return (Number)getAttributeInternal(PLANLINEID);
    }

    /**
     * Sets <code>value</code> as the attribute value for PlanLineId.
     * @param value value to set the PlanLineId
     */
    public void setPlanLineId(Number value) {
        setAttributeInternal(PLANLINEID, value);
    }

    /**
     * Gets the attribute value for PlanId, using the alias name PlanId.
     * @return the PlanId
     */
    public Number getPlanId() {
        return (Number)getAttributeInternal(PLANID);
    }

    /**
     * Sets <code>value</code> as the attribute value for PlanId.
     * @param value value to set the PlanId
     */
    public void setPlanId(Number value) {
        setAttributeInternal(PLANID, value);
    }

    /**
     * Gets the attribute value for VendorId, using the alias name VendorId.
     * @return the VendorId
     */
    public Number getVendorId() {
        return (Number)getAttributeInternal(VENDORID);
    }

    /**
     * Sets <code>value</code> as the attribute value for VendorId.
     * @param value value to set the VendorId
     */
    public void setVendorId(Number value) {
        setAttributeInternal(VENDORID, value);
    }

    /**
     * Gets the attribute value for VendorSiteId, using the alias name VendorSiteId.
     * @return the VendorSiteId
     */
    public Number getVendorSiteId() {
        return (Number)getAttributeInternal(VENDORSITEID);
    }

    /**
     * Sets <code>value</code> as the attribute value for VendorSiteId.
     * @param value value to set the VendorSiteId
     */
    public void setVendorSiteId(Number value) {
        setAttributeInternal(VENDORSITEID, value);
    }

    /**
     * Gets the attribute value for TimeSlot, using the alias name TimeSlot.
     * @return the TimeSlot
     */
    public String getTimeSlot() {
        return (String)getAttributeInternal(TIMESLOT);
    }

    /**
     * Sets <code>value</code> as the attribute value for TimeSlot.
     * @param value value to set the TimeSlot
     */
    public void setTimeSlot(String value) {
        setAttributeInternal(TIMESLOT, value);
    }

    /**
     * Gets the attribute value for Brand, using the alias name Brand.
     * @return the Brand
     */
    public String getBrand() {
        return (String)getAttributeInternal(BRAND);
    }

    /**
     * Sets <code>value</code> as the attribute value for Brand.
     * @param value value to set the Brand
     */
    public void setBrand(String value) {
        setAttributeInternal(BRAND, value);
    }

    /**
     * Gets the attribute value for AdTitle, using the alias name AdTitle.
     * @return the AdTitle
     */
    public String getAdTitle() {
        return (String)getAttributeInternal(ADTITLE);
    }

    /**
     * Sets <code>value</code> as the attribute value for AdTitle.
     * @param value value to set the AdTitle
     */
    public void setAdTitle(String value) {
        setAttributeInternal(ADTITLE, value);
    }

    /**
     * Gets the attribute value for AdDuration, using the alias name AdDuration.
     * @return the AdDuration
     */
    public Number getAdDuration() {
        return (Number)getAttributeInternal(ADDURATION);
    }

    /**
     * Sets <code>value</code> as the attribute value for AdDuration.
     * @param value value to set the AdDuration
     */
    public void setAdDuration(Number value) {
        setAttributeInternal(ADDURATION, value);
    }

    /**
     * Gets the attribute value for Day1, using the alias name Day1.
     * @return the Day1
     */
    public Number getDay1() {
        return (Number)getAttributeInternal(DAY1);
    }

    /**
     * Sets <code>value</code> as the attribute value for Day1.
     * @param value value to set the Day1
     */
    public void setDay1(Number value) {
        setAttributeInternal(DAY1, value);
    }

    /**
     * Gets the attribute value for Day2, using the alias name Day2.
     * @return the Day2
     */
    public Number getDay2() {
        return (Number)getAttributeInternal(DAY2);
    }

    /**
     * Sets <code>value</code> as the attribute value for Day2.
     * @param value value to set the Day2
     */
    public void setDay2(Number value) {
        setAttributeInternal(DAY2, value);
    }

    /**
     * Gets the attribute value for Day3, using the alias name Day3.
     * @return the Day3
     */
    public Number getDay3() {
        return (Number)getAttributeInternal(DAY3);
    }

    /**
     * Sets <code>value</code> as the attribute value for Day3.
     * @param value value to set the Day3
     */
    public void setDay3(Number value) {
        setAttributeInternal(DAY3, value);
    }

    /**
     * Gets the attribute value for Day4, using the alias name Day4.
     * @return the Day4
     */
    public Number getDay4() {
        return (Number)getAttributeInternal(DAY4);
    }

    /**
     * Sets <code>value</code> as the attribute value for Day4.
     * @param value value to set the Day4
     */
    public void setDay4(Number value) {
        setAttributeInternal(DAY4, value);
    }

    /**
     * Gets the attribute value for Day5, using the alias name Day5.
     * @return the Day5
     */
    public Number getDay5() {
        return (Number)getAttributeInternal(DAY5);
    }

    /**
     * Sets <code>value</code> as the attribute value for Day5.
     * @param value value to set the Day5
     */
    public void setDay5(Number value) {
        setAttributeInternal(DAY5, value);
    }

    /**
     * Gets the attribute value for Day6, using the alias name Day6.
     * @return the Day6
     */
    public Number getDay6() {
        return (Number)getAttributeInternal(DAY6);
    }

    /**
     * Sets <code>value</code> as the attribute value for Day6.
     * @param value value to set the Day6
     */
    public void setDay6(Number value) {
        setAttributeInternal(DAY6, value);
    }

    /**
     * Gets the attribute value for Day7, using the alias name Day7.
     * @return the Day7
     */
    public Number getDay7() {
        return (Number)getAttributeInternal(DAY7);
    }

    /**
     * Sets <code>value</code> as the attribute value for Day7.
     * @param value value to set the Day7
     */
    public void setDay7(Number value) {
        setAttributeInternal(DAY7, value);
    }

    /**
     * Gets the attribute value for Day8, using the alias name Day8.
     * @return the Day8
     */
    public Number getDay8() {
        return (Number)getAttributeInternal(DAY8);
    }

    /**
     * Sets <code>value</code> as the attribute value for Day8.
     * @param value value to set the Day8
     */
    public void setDay8(Number value) {
        setAttributeInternal(DAY8, value);
    }

    /**
     * Gets the attribute value for Day9, using the alias name Day9.
     * @return the Day9
     */
    public Number getDay9() {
        return (Number)getAttributeInternal(DAY9);
    }

    /**
     * Sets <code>value</code> as the attribute value for Day9.
     * @param value value to set the Day9
     */
    public void setDay9(Number value) {
        setAttributeInternal(DAY9, value);
    }

    /**
     * Gets the attribute value for Day10, using the alias name Day10.
     * @return the Day10
     */
    public Number getDay10() {
        return (Number)getAttributeInternal(DAY10);
    }

    /**
     * Sets <code>value</code> as the attribute value for Day10.
     * @param value value to set the Day10
     */
    public void setDay10(Number value) {
        setAttributeInternal(DAY10, value);
    }

    /**
     * Gets the attribute value for Day11, using the alias name Day11.
     * @return the Day11
     */
    public Number getDay11() {
        return (Number)getAttributeInternal(DAY11);
    }

    /**
     * Sets <code>value</code> as the attribute value for Day11.
     * @param value value to set the Day11
     */
    public void setDay11(Number value) {
        setAttributeInternal(DAY11, value);
    }

    /**
     * Gets the attribute value for Day12, using the alias name Day12.
     * @return the Day12
     */
    public Number getDay12() {
        return (Number)getAttributeInternal(DAY12);
    }

    /**
     * Sets <code>value</code> as the attribute value for Day12.
     * @param value value to set the Day12
     */
    public void setDay12(Number value) {
        setAttributeInternal(DAY12, value);
    }

    /**
     * Gets the attribute value for Day13, using the alias name Day13.
     * @return the Day13
     */
    public Number getDay13() {
        return (Number)getAttributeInternal(DAY13);
    }

    /**
     * Sets <code>value</code> as the attribute value for Day13.
     * @param value value to set the Day13
     */
    public void setDay13(Number value) {
        setAttributeInternal(DAY13, value);
    }

    /**
     * Gets the attribute value for Day14, using the alias name Day14.
     * @return the Day14
     */
    public Number getDay14() {
        return (Number)getAttributeInternal(DAY14);
    }

    /**
     * Sets <code>value</code> as the attribute value for Day14.
     * @param value value to set the Day14
     */
    public void setDay14(Number value) {
        setAttributeInternal(DAY14, value);
    }

    /**
     * Gets the attribute value for Day15, using the alias name Day15.
     * @return the Day15
     */
    public Number getDay15() {
        return (Number)getAttributeInternal(DAY15);
    }

    /**
     * Sets <code>value</code> as the attribute value for Day15.
     * @param value value to set the Day15
     */
    public void setDay15(Number value) {
        setAttributeInternal(DAY15, value);
    }

    /**
     * Gets the attribute value for Day16, using the alias name Day16.
     * @return the Day16
     */
    public Number getDay16() {
        return (Number)getAttributeInternal(DAY16);
    }

    /**
     * Sets <code>value</code> as the attribute value for Day16.
     * @param value value to set the Day16
     */
    public void setDay16(Number value) {
        setAttributeInternal(DAY16, value);
    }

    /**
     * Gets the attribute value for Day17, using the alias name Day17.
     * @return the Day17
     */
    public Number getDay17() {
        return (Number)getAttributeInternal(DAY17);
    }

    /**
     * Sets <code>value</code> as the attribute value for Day17.
     * @param value value to set the Day17
     */
    public void setDay17(Number value) {
        setAttributeInternal(DAY17, value);
    }

    /**
     * Gets the attribute value for Day18, using the alias name Day18.
     * @return the Day18
     */
    public Number getDay18() {
        return (Number)getAttributeInternal(DAY18);
    }

    /**
     * Sets <code>value</code> as the attribute value for Day18.
     * @param value value to set the Day18
     */
    public void setDay18(Number value) {
        setAttributeInternal(DAY18, value);
    }

    /**
     * Gets the attribute value for Day19, using the alias name Day19.
     * @return the Day19
     */
    public Number getDay19() {
        return (Number)getAttributeInternal(DAY19);
    }

    /**
     * Sets <code>value</code> as the attribute value for Day19.
     * @param value value to set the Day19
     */
    public void setDay19(Number value) {
        setAttributeInternal(DAY19, value);
    }

    /**
     * Gets the attribute value for Day20, using the alias name Day20.
     * @return the Day20
     */
    public Number getDay20() {
        return (Number)getAttributeInternal(DAY20);
    }

    /**
     * Sets <code>value</code> as the attribute value for Day20.
     * @param value value to set the Day20
     */
    public void setDay20(Number value) {
        setAttributeInternal(DAY20, value);
    }

    /**
     * Gets the attribute value for Day21, using the alias name Day21.
     * @return the Day21
     */
    public Number getDay21() {
        return (Number)getAttributeInternal(DAY21);
    }

    /**
     * Sets <code>value</code> as the attribute value for Day21.
     * @param value value to set the Day21
     */
    public void setDay21(Number value) {
        setAttributeInternal(DAY21, value);
    }

    /**
     * Gets the attribute value for Day22, using the alias name Day22.
     * @return the Day22
     */
    public Number getDay22() {
        return (Number)getAttributeInternal(DAY22);
    }

    /**
     * Sets <code>value</code> as the attribute value for Day22.
     * @param value value to set the Day22
     */
    public void setDay22(Number value) {
        setAttributeInternal(DAY22, value);
    }

    /**
     * Gets the attribute value for Day23, using the alias name Day23.
     * @return the Day23
     */
    public Number getDay23() {
        return (Number)getAttributeInternal(DAY23);
    }

    /**
     * Sets <code>value</code> as the attribute value for Day23.
     * @param value value to set the Day23
     */
    public void setDay23(Number value) {
        setAttributeInternal(DAY23, value);
    }

    /**
     * Gets the attribute value for Day24, using the alias name Day24.
     * @return the Day24
     */
    public Number getDay24() {
        return (Number)getAttributeInternal(DAY24);
    }

    /**
     * Sets <code>value</code> as the attribute value for Day24.
     * @param value value to set the Day24
     */
    public void setDay24(Number value) {
        setAttributeInternal(DAY24, value);
    }

    /**
     * Gets the attribute value for Day25, using the alias name Day25.
     * @return the Day25
     */
    public Number getDay25() {
        return (Number)getAttributeInternal(DAY25);
    }

    /**
     * Sets <code>value</code> as the attribute value for Day25.
     * @param value value to set the Day25
     */
    public void setDay25(Number value) {
        setAttributeInternal(DAY25, value);
    }

    /**
     * Gets the attribute value for Day26, using the alias name Day26.
     * @return the Day26
     */
    public Number getDay26() {
        return (Number)getAttributeInternal(DAY26);
    }

    /**
     * Sets <code>value</code> as the attribute value for Day26.
     * @param value value to set the Day26
     */
    public void setDay26(Number value) {
        setAttributeInternal(DAY26, value);
    }

    /**
     * Gets the attribute value for Day27, using the alias name Day27.
     * @return the Day27
     */
    public Number getDay27() {
        return (Number)getAttributeInternal(DAY27);
    }

    /**
     * Sets <code>value</code> as the attribute value for Day27.
     * @param value value to set the Day27
     */
    public void setDay27(Number value) {
        setAttributeInternal(DAY27, value);
    }

    /**
     * Gets the attribute value for Day28, using the alias name Day28.
     * @return the Day28
     */
    public Number getDay28() {
        return (Number)getAttributeInternal(DAY28);
    }

    /**
     * Sets <code>value</code> as the attribute value for Day28.
     * @param value value to set the Day28
     */
    public void setDay28(Number value) {
        setAttributeInternal(DAY28, value);
    }

    /**
     * Gets the attribute value for Day29, using the alias name Day29.
     * @return the Day29
     */
    public Number getDay29() {
        return (Number)getAttributeInternal(DAY29);
    }

    /**
     * Sets <code>value</code> as the attribute value for Day29.
     * @param value value to set the Day29
     */
    public void setDay29(Number value) {
        setAttributeInternal(DAY29, value);
    }

    /**
     * Gets the attribute value for Day30, using the alias name Day30.
     * @return the Day30
     */
    public Number getDay30() {
        return (Number)getAttributeInternal(DAY30);
    }

    /**
     * Sets <code>value</code> as the attribute value for Day30.
     * @param value value to set the Day30
     */
    public void setDay30(Number value) {
        setAttributeInternal(DAY30, value);
    }

    /**
     * Gets the attribute value for Day31, using the alias name Day31.
     * @return the Day31
     */
    public Number getDay31() {
        return (Number)getAttributeInternal(DAY31);
    }

    /**
     * Sets <code>value</code> as the attribute value for Day31.
     * @param value value to set the Day31
     */
    public void setDay31(Number value) {
        setAttributeInternal(DAY31, value);
    }

    /**
     * Gets the attribute value for Day32, using the alias name Day32.
     * @return the Day32
     */
    public Number getDay32() {
        return (Number)getAttributeInternal(DAY32);
    }

    /**
     * Sets <code>value</code> as the attribute value for Day32.
     * @param value value to set the Day32
     */
    public void setDay32(Number value) {
        setAttributeInternal(DAY32, value);
    }

    /**
     * Gets the attribute value for Day33, using the alias name Day33.
     * @return the Day33
     */
    public Number getDay33() {
        return (Number)getAttributeInternal(DAY33);
    }

    /**
     * Sets <code>value</code> as the attribute value for Day33.
     * @param value value to set the Day33
     */
    public void setDay33(Number value) {
        setAttributeInternal(DAY33, value);
    }

    /**
     * Gets the attribute value for Day34, using the alias name Day34.
     * @return the Day34
     */
    public Number getDay34() {
        return (Number)getAttributeInternal(DAY34);
    }

    /**
     * Sets <code>value</code> as the attribute value for Day34.
     * @param value value to set the Day34
     */
    public void setDay34(Number value) {
        setAttributeInternal(DAY34, value);
    }

    /**
     * Gets the attribute value for Day35, using the alias name Day35.
     * @return the Day35
     */
    public Number getDay35() {
        return (Number)getAttributeInternal(DAY35);
    }

    /**
     * Sets <code>value</code> as the attribute value for Day35.
     * @param value value to set the Day35
     */
    public void setDay35(Number value) {
        setAttributeInternal(DAY35, value);
    }

    /**
     * Gets the attribute value for Day36, using the alias name Day36.
     * @return the Day36
     */
    public Number getDay36() {
        return (Number)getAttributeInternal(DAY36);
    }

    /**
     * Sets <code>value</code> as the attribute value for Day36.
     * @param value value to set the Day36
     */
    public void setDay36(Number value) {
        setAttributeInternal(DAY36, value);
    }

    /**
     * Gets the attribute value for Day37, using the alias name Day37.
     * @return the Day37
     */
    public Number getDay37() {
        return (Number)getAttributeInternal(DAY37);
    }

    /**
     * Sets <code>value</code> as the attribute value for Day37.
     * @param value value to set the Day37
     */
    public void setDay37(Number value) {
        setAttributeInternal(DAY37, value);
    }

    /**
     * Gets the attribute value for Day38, using the alias name Day38.
     * @return the Day38
     */
    public Number getDay38() {
        return (Number)getAttributeInternal(DAY38);
    }

    /**
     * Sets <code>value</code> as the attribute value for Day38.
     * @param value value to set the Day38
     */
    public void setDay38(Number value) {
        setAttributeInternal(DAY38, value);
    }

    /**
     * Gets the attribute value for Day39, using the alias name Day39.
     * @return the Day39
     */
    public Number getDay39() {
        return (Number)getAttributeInternal(DAY39);
    }

    /**
     * Sets <code>value</code> as the attribute value for Day39.
     * @param value value to set the Day39
     */
    public void setDay39(Number value) {
        setAttributeInternal(DAY39, value);
    }

    /**
     * Gets the attribute value for Day40, using the alias name Day40.
     * @return the Day40
     */
    public Number getDay40() {
        return (Number)getAttributeInternal(DAY40);
    }

    /**
     * Sets <code>value</code> as the attribute value for Day40.
     * @param value value to set the Day40
     */
    public void setDay40(Number value) {
        setAttributeInternal(DAY40, value);
    }

    /**
     * Gets the attribute value for Day41, using the alias name Day41.
     * @return the Day41
     */
    public Number getDay41() {
        return (Number)getAttributeInternal(DAY41);
    }

    /**
     * Sets <code>value</code> as the attribute value for Day41.
     * @param value value to set the Day41
     */
    public void setDay41(Number value) {
        setAttributeInternal(DAY41, value);
    }

    /**
     * Gets the attribute value for Day42, using the alias name Day42.
     * @return the Day42
     */
    public Number getDay42() {
        return (Number)getAttributeInternal(DAY42);
    }

    /**
     * Sets <code>value</code> as the attribute value for Day42.
     * @param value value to set the Day42
     */
    public void setDay42(Number value) {
        setAttributeInternal(DAY42, value);
    }

    /**
     * Gets the attribute value for Day43, using the alias name Day43.
     * @return the Day43
     */
    public Number getDay43() {
        return (Number)getAttributeInternal(DAY43);
    }

    /**
     * Sets <code>value</code> as the attribute value for Day43.
     * @param value value to set the Day43
     */
    public void setDay43(Number value) {
        setAttributeInternal(DAY43, value);
    }

    /**
     * Gets the attribute value for Day44, using the alias name Day44.
     * @return the Day44
     */
    public Number getDay44() {
        return (Number)getAttributeInternal(DAY44);
    }

    /**
     * Sets <code>value</code> as the attribute value for Day44.
     * @param value value to set the Day44
     */
    public void setDay44(Number value) {
        setAttributeInternal(DAY44, value);
    }

    /**
     * Gets the attribute value for Day45, using the alias name Day45.
     * @return the Day45
     */
    public Number getDay45() {
        return (Number)getAttributeInternal(DAY45);
    }

    /**
     * Sets <code>value</code> as the attribute value for Day45.
     * @param value value to set the Day45
     */
    public void setDay45(Number value) {
        setAttributeInternal(DAY45, value);
    }

    /**
     * Gets the attribute value for Day46, using the alias name Day46.
     * @return the Day46
     */
    public Number getDay46() {
        return (Number)getAttributeInternal(DAY46);
    }

    /**
     * Sets <code>value</code> as the attribute value for Day46.
     * @param value value to set the Day46
     */
    public void setDay46(Number value) {
        setAttributeInternal(DAY46, value);
    }

    /**
     * Gets the attribute value for Day47, using the alias name Day47.
     * @return the Day47
     */
    public Number getDay47() {
        return (Number)getAttributeInternal(DAY47);
    }

    /**
     * Sets <code>value</code> as the attribute value for Day47.
     * @param value value to set the Day47
     */
    public void setDay47(Number value) {
        setAttributeInternal(DAY47, value);
    }

    /**
     * Gets the attribute value for Day48, using the alias name Day48.
     * @return the Day48
     */
    public Number getDay48() {
        return (Number)getAttributeInternal(DAY48);
    }

    /**
     * Sets <code>value</code> as the attribute value for Day48.
     * @param value value to set the Day48
     */
    public void setDay48(Number value) {
        setAttributeInternal(DAY48, value);
    }

    /**
     * Gets the attribute value for Day49, using the alias name Day49.
     * @return the Day49
     */
    public Number getDay49() {
        return (Number)getAttributeInternal(DAY49);
    }

    /**
     * Sets <code>value</code> as the attribute value for Day49.
     * @param value value to set the Day49
     */
    public void setDay49(Number value) {
        setAttributeInternal(DAY49, value);
    }

    /**
     * Gets the attribute value for Day50, using the alias name Day50.
     * @return the Day50
     */
    public Number getDay50() {
        return (Number)getAttributeInternal(DAY50);
    }

    /**
     * Sets <code>value</code> as the attribute value for Day50.
     * @param value value to set the Day50
     */
    public void setDay50(Number value) {
        setAttributeInternal(DAY50, value);
    }

    /**
     * Gets the attribute value for Day51, using the alias name Day51.
     * @return the Day51
     */
    public Number getDay51() {
        return (Number)getAttributeInternal(DAY51);
    }

    /**
     * Sets <code>value</code> as the attribute value for Day51.
     * @param value value to set the Day51
     */
    public void setDay51(Number value) {
        setAttributeInternal(DAY51, value);
    }

    /**
     * Gets the attribute value for Day52, using the alias name Day52.
     * @return the Day52
     */
    public Number getDay52() {
        return (Number)getAttributeInternal(DAY52);
    }

    /**
     * Sets <code>value</code> as the attribute value for Day52.
     * @param value value to set the Day52
     */
    public void setDay52(Number value) {
        setAttributeInternal(DAY52, value);
    }

    /**
     * Gets the attribute value for Day53, using the alias name Day53.
     * @return the Day53
     */
    public Number getDay53() {
        return (Number)getAttributeInternal(DAY53);
    }

    /**
     * Sets <code>value</code> as the attribute value for Day53.
     * @param value value to set the Day53
     */
    public void setDay53(Number value) {
        setAttributeInternal(DAY53, value);
    }

    /**
     * Gets the attribute value for Day54, using the alias name Day54.
     * @return the Day54
     */
    public Number getDay54() {
        return (Number)getAttributeInternal(DAY54);
    }

    /**
     * Sets <code>value</code> as the attribute value for Day54.
     * @param value value to set the Day54
     */
    public void setDay54(Number value) {
        setAttributeInternal(DAY54, value);
    }

    /**
     * Gets the attribute value for Day55, using the alias name Day55.
     * @return the Day55
     */
    public Number getDay55() {
        return (Number)getAttributeInternal(DAY55);
    }

    /**
     * Sets <code>value</code> as the attribute value for Day55.
     * @param value value to set the Day55
     */
    public void setDay55(Number value) {
        setAttributeInternal(DAY55, value);
    }

    /**
     * Gets the attribute value for Day56, using the alias name Day56.
     * @return the Day56
     */
    public Number getDay56() {
        return (Number)getAttributeInternal(DAY56);
    }

    /**
     * Sets <code>value</code> as the attribute value for Day56.
     * @param value value to set the Day56
     */
    public void setDay56(Number value) {
        setAttributeInternal(DAY56, value);
    }

    /**
     * Gets the attribute value for Day57, using the alias name Day57.
     * @return the Day57
     */
    public Number getDay57() {
        return (Number)getAttributeInternal(DAY57);
    }

    /**
     * Sets <code>value</code> as the attribute value for Day57.
     * @param value value to set the Day57
     */
    public void setDay57(Number value) {
        setAttributeInternal(DAY57, value);
    }

    /**
     * Gets the attribute value for Day58, using the alias name Day58.
     * @return the Day58
     */
    public Number getDay58() {
        return (Number)getAttributeInternal(DAY58);
    }

    /**
     * Sets <code>value</code> as the attribute value for Day58.
     * @param value value to set the Day58
     */
    public void setDay58(Number value) {
        setAttributeInternal(DAY58, value);
    }

    /**
     * Gets the attribute value for Day59, using the alias name Day59.
     * @return the Day59
     */
    public Number getDay59() {
        return (Number)getAttributeInternal(DAY59);
    }

    /**
     * Sets <code>value</code> as the attribute value for Day59.
     * @param value value to set the Day59
     */
    public void setDay59(Number value) {
        setAttributeInternal(DAY59, value);
    }

    /**
     * Gets the attribute value for Day60, using the alias name Day60.
     * @return the Day60
     */
    public Number getDay60() {
        return (Number)getAttributeInternal(DAY60);
    }

    /**
     * Sets <code>value</code> as the attribute value for Day60.
     * @param value value to set the Day60
     */
    public void setDay60(Number value) {
        setAttributeInternal(DAY60, value);
    }

    /**
     * Gets the attribute value for RateType, using the alias name RateType.
     * @return the RateType
     */
    public Number getRateType() {
        return (Number)getAttributeInternal(RATETYPE);
    }

    /**
     * Sets <code>value</code> as the attribute value for RateType.
     * @param value value to set the RateType
     */
    public void setRateType(Number value) {
        setAttributeInternal(RATETYPE, value);
    }

    /**
     * Gets the attribute value for RatePerMinute, using the alias name RatePerMinute.
     * @return the RatePerMinute
     */
    public Number getRatePerMinute() {
        return (Number)getAttributeInternal(RATEPERMINUTE);
    }

    /**
     * Sets <code>value</code> as the attribute value for RatePerMinute.
     * @param value value to set the RatePerMinute
     */
    public void setRatePerMinute(Number value) {
        setAttributeInternal(RATEPERMINUTE, value);
    }

    /**
     * Gets the attribute value for DiscountPerMinute, using the alias name DiscountPerMinute.
     * @return the DiscountPerMinute
     */
    public Number getDiscountPerMinute() {
        return (Number)getAttributeInternal(DISCOUNTPERMINUTE);
    }

    /**
     * Sets <code>value</code> as the attribute value for DiscountPerMinute.
     * @param value value to set the DiscountPerMinute
     */
    public void setDiscountPerMinute(Number value) {
        setAttributeInternal(DISCOUNTPERMINUTE, value);
    }

    /**
     * Gets the attribute value for PremiumPercentAge, using the alias name PremiumPercentAge.
     * @return the PremiumPercentAge
     */
    public Number getPremiumPercentAge() {
        return (Number)getAttributeInternal(PREMIUMPERCENTAGE);
    }

    /**
     * Sets <code>value</code> as the attribute value for PremiumPercentAge.
     * @param value value to set the PremiumPercentAge
     */
    public void setPremiumPercentAge(Number value) {
        setAttributeInternal(PREMIUMPERCENTAGE, value);
    }

    /**
     * Gets the attribute value for ActualRate, using the alias name ActualRate.
     * @return the ActualRate
     */
    public Number getActualRate() {
        return (Number)getAttributeInternal(ACTUALRATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for ActualRate.
     * @param value value to set the ActualRate
     */
    public void setActualRate(Number value) {
        setAttributeInternal(ACTUALRATE, value);
    }

    /**
     * Gets the attribute value for CreditNoteAmount, using the alias name CreditNoteAmount.
     * @return the CreditNoteAmount
     */
    public String getCreditNoteAmount() {
        return (String)getAttributeInternal(CREDITNOTEAMOUNT);
    }

    /**
     * Sets <code>value</code> as the attribute value for CreditNoteAmount.
     * @param value value to set the CreditNoteAmount
     */
    public void setCreditNoteAmount(String value) {
        setAttributeInternal(CREDITNOTEAMOUNT, value);
    }

    /**
     * Gets the attribute value for GstPercentAge, using the alias name GstPercentAge.
     * @return the GstPercentAge
     */
    public String getGstPercentAge() {
        return (String)getAttributeInternal(GSTPERCENTAGE);
    }

    /**
     * Sets <code>value</code> as the attribute value for GstPercentAge.
     * @param value value to set the GstPercentAge
     */
    public void setGstPercentAge(String value) {
        setAttributeInternal(GSTPERCENTAGE, value);
    }

    /**
     * Gets the attribute value for GstClient, using the alias name GstClient.
     * @return the GstClient
     */
    public String getGstClient() {
        return (String)getAttributeInternal(GSTCLIENT);
    }

    /**
     * Sets <code>value</code> as the attribute value for GstClient.
     * @param value value to set the GstClient
     */
    public void setGstClient(String value) {
        setAttributeInternal(GSTCLIENT, value);
    }

    /**
     * Gets the attribute value for AgencyCommissionClient, using the alias name AgencyCommissionClient.
     * @return the AgencyCommissionClient
     */
    public String getAgencyCommissionClient() {
        return (String)getAttributeInternal(AGENCYCOMMISSIONCLIENT);
    }

    /**
     * Sets <code>value</code> as the attribute value for AgencyCommissionClient.
     * @param value value to set the AgencyCommissionClient
     */
    public void setAgencyCommissionClient(String value) {
        setAttributeInternal(AGENCYCOMMISSIONCLIENT, value);
    }

    /**
     * Gets the attribute value for CreatedBy, using the alias name CreatedBy.
     * @return the CreatedBy
     */
    public Number getCreatedBy() {
        return (Number)getAttributeInternal(CREATEDBY);
    }

    /**
     * Sets <code>value</code> as the attribute value for CreatedBy.
     * @param value value to set the CreatedBy
     */
    public void setCreatedBy(Number value) {
        setAttributeInternal(CREATEDBY, value);
    }

    /**
     * Gets the attribute value for CreationDate, using the alias name CreationDate.
     * @return the CreationDate
     */
    public Date getCreationDate() {
        return (Date)getAttributeInternal(CREATIONDATE);
    }


    /**
     * Gets the attribute value for UpdatedBy, using the alias name UpdatedBy.
     * @return the UpdatedBy
     */
    public Number getUpdatedBy() {
        return (Number)getAttributeInternal(UPDATEDBY);
    }

    /**
     * Sets <code>value</code> as the attribute value for UpdatedBy.
     * @param value value to set the UpdatedBy
     */
    public void setUpdatedBy(Number value) {
        setAttributeInternal(UPDATEDBY, value);
    }

    /**
     * Gets the attribute value for UpdatedDate, using the alias name UpdatedDate.
     * @return the UpdatedDate
     */
    public Date getUpdatedDate() {
        return (Date)getAttributeInternal(UPDATEDDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for UpdatedDate.
     * @param value value to set the UpdatedDate
     */
    public void setUpdatedDate(Date value) {
        setAttributeInternal(UPDATEDDATE, value);
    }

    /**
     * getAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param attrDef the attribute

     * @return the attribute value
     * @throws Exception
     */
    protected Object getAttrInvokeAccessor(int index,
                                           AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            return AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].get(this);
        }
        return super.getAttrInvokeAccessor(index, attrDef);
    }

    /**
     * setAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param value the value to assign to the attribute
     * @param attrDef the attribute

     * @throws Exception
     */
    protected void setAttrInvokeAccessor(int index, Object value,
                                         AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].put(this, value);
            return;
        }
        super.setAttrInvokeAccessor(index, value, attrDef);
    }

    /**
     * @param planLineId key constituent

     * @return a Key object based on given key constituents.
     */
    public static Key createPrimaryKey(Number planLineId) {
        return new Key(new Object[]{planLineId});
    }


}
